"""回答データのカラム定義（Google Sheets / ローカル保存で共通）"""

RESPONSE_HEADERS = [
    "response_id",
    "submitted_at",
    "q1_rank1",
    "q1_rank2",
    "q1_rank3",
    "q1_score1",
    "q1_score2",
    "q1_score3",
    "q1_other_text",
    "q2_rank1",
    "q2_rank2",
    "q2_rank3",
    "q2_score1",
    "q2_score2",
    "q2_score3",
    "q2_other_text",
    "q3_1_child_image",
    "q3_2_child_count",
    "q3_3_child_feelings",
    "q4_has_lover",
    "q4_1_marriage_intent",
    "q4_2_reasons",
    "q5_1_marriage_wish",
    "q5_2_reason",
    "q6_app_intent",
    "q6_1_reason",
    "age",
    "gender",
    "affiliation",
    "living",
    "siblings",
    "income",
]
